# Generated by Django 5.0.6 on 2024-07-17 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.png', upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=100)),
                ('password_confirm', models.CharField(max_length=100, verbose_name='confirm password')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nativel', models.CharField(max_length=100)),
                ('situation', models.CharField(choices=[('T', 'People tell me that I have a strong accent'), ('A', 'People ask me to repeat what I said'), ('S', 'People speak too fast for me to understand')], max_length=1, verbose_name='Which situation is more common for you?')),
                ('method', models.CharField(choices=[('B', 'Be better at my current job and get paid more'), ('F', 'Find a new job'), ('I', 'Improve my networking and relationships'), ('A', 'Adapt more easily to American culture')], max_length=1, verbose_name=" Imagine you speak a better English today. What can you do that you couldn't do before?")),
                ('usa', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=5, verbose_name='Do you live in the U.S.?')),
                ('speak', models.CharField(choices=[('80', '80% of the time or more'), ('50', 'about 50% of the time'), ('10', '10% of the time or less')], max_length=2, verbose_name='How often do you speak English?')),
                ('minute', models.CharField(choices=[('5', '5 - 10 mins'), ('15', '15 - 20 minute'), ('30', '30 mins'), ('more', 'More than that')], max_length=4, verbose_name='How much time each day can you spend improving your English speaking skills?')),
                ('register', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
