# Generated by Django 5.0.6 on 2024-07-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=100)),
                ('password_confirm', models.CharField(max_length=100, verbose_name='Confirme password')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nativel', models.CharField(max_length=100)),
                ('people', models.CharField(choices=[('H', 'have told me that I have a strong accent.'), ('O', 'often ask me to repeat what I said'), ('S', 'speak too fast, and I have a hard time understanding.')], max_length=1)),
                ('method', models.CharField(choices=[('B', 'Be better at my current job and get paid more'), ('F', 'Find a new job'), ('I', 'Improve my networking and relationships'), ('T', 'To get better immersed in the American culture')], max_length=1)),
                ('usa', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=5)),
                ('speak', models.CharField(choices=[('80', '80% of the time or more'), ('50', 'about 50% of the time'), ('10', '10% of the time or less')], max_length=2)),
                ('minute', models.CharField(choices=[('5', '5-10 mins'), ('15', '15-20 minute'), ('30', '30 mins'), ('more', 'More than that')], max_length=4)),
                ('register', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='users.register')),
            ],
        ),
    ]
