# Generated by Django 5.0.6 on 2024-07-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetail',
            name='nativel',
            field=models.CharField(max_length=100),
        ),
    ]
