# Generated by Django 5.0.6 on 2024-07-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_checkoutsessionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
