# Generated by Django 5.0.6 on 2024-07-10 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_register_first_name_remove_register_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetail',
            name='method',
            field=models.CharField(choices=[('B', 'Be better at my current job and get paid more'), ('F', 'Find a new job'), ('I', 'Improve my networking and relationships'), ('T', 'To get better immersed in the American culture')], max_length=1, verbose_name="Imagine you speak a better English today. What can you do that you couldn't do before?"),
        ),
        migrations.AlterField(
            model_name='customdetail',
            name='minute',
            field=models.CharField(choices=[('5', '5-10 mins'), ('15', '15-20 minute'), ('30', '30 mins'), ('more', 'More than that')], max_length=4, verbose_name='How much time each day can you spend improving your English speaking skills?'),
        ),
        migrations.AlterField(
            model_name='customdetail',
            name='people',
            field=models.CharField(choices=[('H', 'have told me that I have a strong accent.'), ('O', 'often ask me to repeat what I said'), ('S', 'speak too fast, and I have a hard time understanding.')], max_length=1, verbose_name='People'),
        ),
        migrations.AlterField(
            model_name='customdetail',
            name='speak',
            field=models.CharField(choices=[('80', '80% of the time or more'), ('50', 'about 50% of the time'), ('10', '10% of the time or less')], max_length=2, verbose_name='How often do you speak English?'),
        ),
        migrations.AlterField(
            model_name='customdetail',
            name='usa',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], max_length=5, verbose_name='Do you live in the U.S.?'),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=30, verbose_name='What is your native language?'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_id', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
