# Generated by Django 5.0.6 on 2024-07-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customdetail_nativel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdetail',
            name='minute',
            field=models.CharField(choices=[('5', '5 - 10 mins'), ('15', '15 - 20 minute'), ('30', '30 mins'), ('more', 'More than that')], max_length=4, verbose_name='How much time each day can you spend improving your English speaking skills?'),
        ),
    ]
