# Generated by Django 5.0.6 on 2024-07-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customdetail_method_alter_customdetail_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Username'),
        ),
    ]
