# Generated by Django 5.0.6 on 2024-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_register_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
