# Generated by Django 5.0.6 on 2024-07-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_plan_subscription_delete_checkoutsessionrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
