# Generated by Django 5.0.6 on 2024-07-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptionplan_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='payment_link',
        ),
    ]
