# Generated by Django 5.0.6 on 2024-07-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_subscriptionplan_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
