# Generated by Django 5.0.6 on 2024-07-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_image',
            field=models.FileField(blank=True, null=True, upload_to='lesson_images/'),
        ),
    ]
