# Generated by Django 5.0.6 on 2024-07-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='content',
            name='audio_file',
        ),
    ]
