# Generated by Django 5.0.6 on 2024-07-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_lesson',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_module',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='module.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='module.lesson'),
        ),
    ]
