# Generated by Django 5.0.6 on 2024-06-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
