# Generated by Django 5.0.6 on 2024-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_module_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='modules',
            field=models.ManyToManyField(related_name='sections', to='module.module'),
        ),
    ]
