# Generated by Django 5.0.6 on 2024-06-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_section_modules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='modules',
            new_name='module',
        ),
    ]
