# Generated by Django 5.0.6 on 2024-06-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_content_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='unit',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='module',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
        migrations.RemoveField(
            model_name='module',
            name='details',
        ),
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Lesson Images')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='module.module')),
            ],
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
