# Generated by Django 5.0.6 on 2024-06-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0008_remove_module_unit_rename_module_section_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='unit',
            new_name='module',
        ),
    ]
