# Generated by Django 4.1 on 2024-06-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='captcha',
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(max_length=200, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject'),
        ),
    ]
